/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "chebyshev.h"

bool_t
xdr_MatrixData (XDR *xdrs, MatrixData *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->matrix.matrix_val, (u_int *) &objp->matrix.matrix_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SolverResult (XDR *xdrs, SolverResult *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->time_ms))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->iterations))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->solution.solution_val, (u_int *) &objp->solution.solution_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}
