/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHEBYSHEV_H_RPCGEN
#define _CHEBYSHEV_H_RPCGEN

#include <tirpc/rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct MatrixData {
	int n;
	int mode;
	struct {
		u_int matrix_len;
		double *matrix_val;
	} matrix;
};
typedef struct MatrixData MatrixData;

struct SolverResult {
	int n;
	double time_ms;
	int iterations;
	struct {
		u_int solution_len;
		double *solution_val;
	} solution;
};
typedef struct SolverResult SolverResult;

#define CHEBYSHEV_SOLVER 0x20000001
#define CHEBYSHEV_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SOLVE_LINEAR_SYSTEM 1
extern  SolverResult * solve_linear_system_1(MatrixData *, CLIENT *);
extern  SolverResult * solve_linear_system_1_svc(MatrixData *, struct svc_req *);
extern int chebyshev_solver_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SOLVE_LINEAR_SYSTEM 1
extern  SolverResult * solve_linear_system_1();
extern  SolverResult * solve_linear_system_1_svc();
extern int chebyshev_solver_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_MatrixData (XDR *, MatrixData*);
extern  bool_t xdr_SolverResult (XDR *, SolverResult*);

#else /* K&R C */
extern bool_t xdr_MatrixData ();
extern bool_t xdr_SolverResult ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHEBYSHEV_H_RPCGEN */
