/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "chebyshev.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

SolverResult *
solve_linear_system_1(MatrixData *argp, CLIENT *clnt)
{
	static SolverResult clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SOLVE_LINEAR_SYSTEM,
		(xdrproc_t) xdr_MatrixData, (caddr_t) argp,
		(xdrproc_t) xdr_SolverResult, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
